### ISSUE TITLE
Device documentation is missing QS_CI metric

### ISSUE THREAD

**Issue by mimre25** [meteocontrol/meteocontrol.github.io#6]
Hi,

when looking through the import specification the metric `QS_CI` is missing. 
For example, the [inverter specs](https://github.com/meteocontrol/meteocontrol.github.io/blob/master/import-specification/devices/inverter.md) list `QS_TX` and `QS_RX`, but I'm wondering what `QS_CI` stands for?

**Comment by DerayGa** [comment]
1. `QS_CI ` stand for **Communication Quality**  
1. it's not missing but not a public one. (means not recommend to import)
