### ISSUE TITLE
Abbreviations for direct and diffuse irradiance

### ISSUE THREAD

**Issue by jamesmhbarry** [meteocontrol/meteocontrol.github.io#7]
I tried importing data via CSV and FTP push using the abbreviations SRAD_DIRECT and SRAD_DIFFUSE, but the data did not show up in the VCOM portal.

**Comment by DerayGa** [comment]
please kindly provide CSV file, or system key in VCOM(I can find CSV files there), I’ll take a look this issue.

**Comment by jamesmhbarry** [comment]
The system key is 115QV, and the uploaded CSV file is called "78926053_cams_GS0000_20240908_20240915.csv", which was uploaded at 08:44:53 this morning. I subsequently uploaded a new CSV to overwrite it, using the abbreviation "SRAD" instead.

**Comment by DerayGa** [comment]
I found 4 meteo devices with SRAD value, data import looks fine to me.  

<img width="682" alt="SRAD" src="https://github.com/user-attachments/assets/972f007b-65a5-4219-ae34-eeb0a745424b">

since you change abbreviation from SRAD_DIRECT and SRAD_DIFFUSE to SRAD.  
I also update those changes in VCOM by
- copy above value to SRAD
- remove SRAD_DIRECT and SRAD_DIFFUSE

I think it's because there are too many csv files (since 2021 Feb), so live data is not import as expected.  
But all csv files are done import at this moment

BTW, data stopped at `2024-09-16 02:00:00`

**Comment by jamesmhbarry** [comment]
Sure, I changed them all to SRAD to make it work. ;)

The point is, in your specification, you state [here](https://github.com/meteocontrol/meteocontrol.github.io/blob/master/import-specification/devices/meteo.md) that it should be possible to use SRAD_DIRECT and SRAD_DIFFUSE. I tried these abbreviations but the data did not appear. This was before I uploaded a lot of data (from Feb 2021).

Yes, since it is CAMS data, the live data is only available up until 2 days before the present.

**Comment by DerayGa** [comment]
Early I checked import result, SRAD_DIRECT and SRAD_DIFFUSE were successfully imported.  
if you like you can import them again.  

it's not appear probably because of cache or something.  
but data importing is correct.

**Comment by DerayGa** [comment]
maybe it's UI/UX issue, SRAD_DIRECT and SRAD_DIFFUSE is not common abbreviation that will display by default.   
to see those value need using `Sensors` > `Diagram creator`  

<img width="490" alt="Diagram creator" src="https://github.com/user-attachments/assets/b4d28b3d-c7a4-4eb6-ae1c-4aa7c2c98cfa">

**Comment by jamesmhbarry** [comment]
Thanks for the comments. Yes maybe it was just an issue with the display in VCOM. I didn't see it under irradiance so perhaps I should have looked in the diagram creator. However now I deleted the original data and imported it all with SRAD as abbreviation. But good to know that it was indeed imported correctly.

This relates to a similar topic I have discussed with meteocontrol - it would make sense to have more abbreviations for irradiance, for instance "SRAD_TILTED". Otherwise one is forced to use the sensor name to describe the irradiance.

**Comment by DerayGa** [comment]
ping @moerks @albert361, regarding `SRAD_TILTED`  

will let you know if we added new irradiance  values.

**Comment by jamesmhbarry** [comment]
Alright, thanks for the help!

Yes, it would be good to differentiate between SRAD_HORIZONTAL, SRAD_TILTED, etc. :)

The same could be said for T_AMBIENT and T_MODULE, however if you go down this road there may be a lot more temperature categories that come about!

**Comment by albert361** [comment]
@jamesmhbarry We will discuss internally, thank you for the suggestion.
